name: Convert model
on:
  workflow_dispatch:
    inputs:
      model_url:
        description: 'Model URL'
        type: string
        default: 'kaggle/esrgan-tf2/tfLite/esrgan-tf2'
        required: true

jobs:
  download-model:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Download model
        run: |
          python convert_tflite.py ${{ inputs.model_url }}
          echo "MODEL_NAME=$(cat model_name.txt)" >> $GITHUB_ENV
      - name: Upload model
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: build/**
      - name: Archive
        shell: sh
        run: |
          ls
          cd build
          zip -r "../model.zip" *
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.MODEL_NAME }}
          files: |
            model.zip
          generate_release_notes: false
          tag_name: ${{ env.MODEL_NAME }}
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
